apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: audiobookshelf-config
  namespace: longhorn-system
spec:
  size: "1073741824" # 1Gi
  frontend: blockdev
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: audiobookshelf-metadata
  namespace: longhorn-system
spec:
  size: "5368709120" # 5Gi
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: audiobookshelf-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: audiobookshelf-metadata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: audiobookshelf-config
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: audiobookshelf-metadata
  storageClassName: longhorn
