apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf-app
  namespace: flux-system
spec:
  path: ./flux/apps/audiobookshelf/app
  prune: true
  interval: 10m
  dependsOn:
    - name: audiobookshelf-volumes
  sourceRef:
    kind: GitRepository
    name: flux-system
