apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: librofm-dl-local
  namespace: default
spec:
  entryPoints:
    - local
  routes:
    - match: Host(`librofm-dl.home`)
      kind: Rule
      services:
        - name: librofm-dl
          port: 80
