apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arr/flux-kustomization.yaml
  - bike-db/flux-kustomization.yaml
  - budget/flux-kustomization.yaml
  - homeassistant/flux-kustomization.yaml
  - immich/flux-kustomization.yaml
  - media/flux-kustomization.yaml
  - nextcloud/flux-kustomization.yaml
  - nodered/flux-kustomization.yaml
  - vaultwarden/flux-kustomization.yaml
