apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arr/flux-kustomization.yaml
  - audiobookshelf/flux-kustomization.yaml
  - budget/flux-kustomization.yaml
  - jellyfin/flux-kustomization.yaml
  - kavita/flux-kustomization.yaml
  - mybibliotheca/flux-kustomization.yaml
  - homeassistant/flux-kustomization.yaml
  - immich/flux-kustomization.yaml
  - nodered/flux-kustomization.yaml
  - vaultwarden/flux-kustomization.yaml
