apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr/flux-kustomization.yaml
  - lidarr/flux-kustomization.yaml
  - radarr/flux-kustomization.yaml
  - readarr/flux-kustomization.yaml
  - sonarr/flux-kustomization.yaml
  - vpn/flux-kustomization.yaml
