apiVersion: batch/v1
kind: Job
metadata:
  name: pg-list-dbs
spec:
  template:
    spec:
      nodeSelector:
        network: fast
      restartPolicy: Never
      containers:
        - name: pg-list-dbs
          image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
          env:
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          command: 
            - sh
            - -c
            - psql
              --host=$PGHOST
              --dbname=$PGDATABASE
              --port=$PGPORT
              --username=$PGUSERNAME
              --command="\\list"
  backoffLimit: 4
