apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  labels:
    app: prometheus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: datasphere
    path: /Root/Volumes/prometheus
