apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: default
spec:
  type: ExternalName
  externalName: longhorn-frontend.longhorn-system.svc.cluster.local
  ports:
    - name: http
      port: 8080
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.local`)
      kind: Rule
      services:
        - name: longhorn-frontend
          kind: Service
          port: 8080
