apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-nextcloud
  namespace: default
spec:
  secretName: cert-nextcloud
  dnsNames:
    - arlodev.co.uk
    - www.arlodev.co.uk
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: external-nextcloud
  namespace: default
spec:
  ports:
    - port: 8001
      name: nextcloud
  type: ExternalName
  externalName: arlo-laptop1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-nextcloud-local
  namespace: default
spec:
  entryPoints:
    - local
  routes:
    - match: Host(`nc.home`)
      kind: Rule
      services:
        - name: external-nextcloud
          port: 8001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-nextcloud-web
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`arlodev.co.uk`)
      kind: Rule
      services:
        - name: external-nextcloud
          port: 8001
    - match: Host(`www.arlodev.co.uk`)
      kind: Rule
      services:
        - name: external-nextcloud
          port: 8001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-nextcloud-websecure
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`arlodev.co.uk`)
      kind: Rule
      services:
        - name: external-nextcloud
          port: 8001
    - match: Host(`www.arlodev.co.uk`)
      kind: Rule
      services:
        - name: external-nextcloud
          port: 8001
  tls:
    secretName: cert-nextcloud
