apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ollama/flux-kustomization.yaml
  - open-terminal/flux-kustomization.yaml
  - open-webui/flux-kustomization.yaml
  - openclaw/flux-kustomization.yaml
