apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: default
  values:
    service:
      enabled: true
      type: NodePort
      ports:
        web:
          port: 80
          targetPort: 80
          # This is currently ignored for some reason
          nodePort: 30001
        websecure:
          port: 443
          targetPort: 443
          # This is currently ignored for some reason
          nodePort: 30002
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
