apiVersion: v1
kind: Node
metadata:
  name: datasphere
  labels:
    network: slow
    transcode: false
---
apiVersion: v1
kind: Node
metadata:
  name: neptune
  labels:
    network: fast
    transcode: false
---
apiVersion: v1
kind: Node
metadata:
  name: pluto
  labels:
    network: fast
    transcode: false
---
apiVersion: v1
kind: Node
metadata:
  name: arlo-laptop1
  labels:
    network: fast
    transcode: true
