keys:
  - &primary age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
        - *primary
