apiVersion: v1
kind: Secret
metadata:
    name: librofm-dl-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CTi3t+fD8T2EUP3QcT6WJps=,iv:ddJhZg3L4UBRJ67wTHn6PBY/7w8Afw0QS3lzWExtJFU=,tag:pzxsFrtW+nIb5k8KSwA9vg==,type:str]
    password: ENC[AES256_GCM,data:32+to3TOkudu2atwC3pT3YY/VKteeG9TRIwV6H9aM6fd3gHbv17K4qwbKFl7A46FueZiJFqjAQ==,iv:Onx7lA0rVffzgb3r+fV0Ih+cbDeXK7H50CLNIx9nTCU=,tag:J/JW9EbCLrG7F9QH2e+NxA==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T17:01:08Z"
    mac: ENC[AES256_GCM,data:LG4B5dNyUDRe2JAlWMfL9sW2edOwxTQzE2NXOclPX6Awxk73CghWp7yP1hyNFH6rXriAvDnYROWE1at53WxLpmkrTjcOvrbPyxOKLvgHBJF38eFgxoZrHCpVlQ+1soWWY+xkMIXWr5bYfM5f1aJHf1PD2jMmWD4YJGLrsDvmyC8=,iv:RFnaqf7jR2l3MlMH3ilKo4AWj9TKtjc2hZZzQovpNrc=,tag:/VDeKUrpkqd9FbBdp6dUGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
