apiVersion: v1
kind: Secret
metadata:
    name: librofm-dl-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CTi3t+fD8T2EUP3QcT6WJps=,iv:ddJhZg3L4UBRJ67wTHn6PBY/7w8Afw0QS3lzWExtJFU=,tag:pzxsFrtW+nIb5k8KSwA9vg==,type:str]
    password: ENC[AES256_GCM,data:IF5Rctmdc1SE/4+YdrLGvpMKs2b36g==,iv:9B5sMLmEQtcliIAU89O7a1UxJfsNfwSpWpOrW9xbNZg=,tag:movIhAM1dSCZ89wG2xEMDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T22:26:53Z"
    mac: ENC[AES256_GCM,data:liWAe5e6m6BjvZ/pm0LbnjmdNiU5c6gBEBSsTG0jdDbIVcKE73rpU4vOnb0lTICRpWDvW7TzvXCMuVT14SFKvAK2QlXrGNAd8oVRXqGCj7MxPbGbQlSuEGiNh2j+PIci3c8xeCR/0Vt3zEQUHVtTnK+hJGi/IYDyycZMiMNVC1s=,iv:w0xbwpYpYLNc3ZKWWhoJnNoDckVmsfxJFlsvocabSRk=,tag:9+UGnouI5SCLWlmHQWzMyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
