apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
type: Opaque
stringData:
    whiteboard-jwt: ENC[AES256_GCM,data:5agOQgjaw0T/TtTaz9m/u4o9SLmMlkS9Cqha8BOmLPm4t3RTh6Z4f0fnaMKyDdOHZXPBOp5zog==,iv:tlnKbYW2gRLRzZbkQpT1cLD19W86xVVy8K7B1cSV03g=,tag:nrLeGAw39BoLa7h7mtTLNg==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T16:04:12Z"
    mac: ENC[AES256_GCM,data:gFEiox5kLjPH1wjYSul8ZNlr7DyCa4kHvKX+9jMYuPcG9JTQ6/pLvm8reKy/CveBeNbZ8NXAtNivDPssdXAGQnGDlxe+Gt7na3mjqs7Cij8QFHAipVackO0/Ss71pIUsoE/c7hhMvdl/BjGXO4jb1KYJqAOtV5YjDqAbOvrKXX0=,iv:16bO8yBJkZCKsXVUpDzj76/JaZOURBanOpOw1GCaNWo=,tag:mPuFCbZ6HIWEyCLqXqqQbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
