apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
type: Opaque
stringData:
    whiteboard-jwt: ENC[AES256_GCM,data:mDEanhM9DrR4DJymTyhnkM1mjKOTjFBUARSgmxrGCMnTVtTZGqb83XXJWo/TtQ==,iv:Pw9r/52OUoKTzfdVRQXly/Z5RnNqHU/gUPPrr3dDk60=,tag:ah79hCyJFvi2z/qqYfvA0Q==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T16:37:42Z"
    mac: ENC[AES256_GCM,data:uNgodxdqmppNRD0xBAcob+sNejpXg5dAWScrD3WXL4h7RhJzy6edSRTlzTuGoRgAE0hpLU0G6AGOkk5MstDBXKGvw6L3OWBaLb8w9xYDXKQnadeNFRyv/Ncgwpku+o+GTXVB595OfVhLfl6dIDWbDr5ESXDr/lX9xy5/PKEFb58=,iv:padahsiwLt8fJD3+0N+KwRRjy7yG20vFdXBbsZieLf8=,tag:nqwSeTyfdRPdSqLeuUznTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
