apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:p06Qul5Z0kyE2FoWWrE=,iv:zNsImxkCt/d7/wpy1gLWtRbmBnSaf03yQDMxtq45xa4=,tag:qIpWcD0Ghov7GHI8l7geWg==,type:str]
    password: ENC[AES256_GCM,data:hdPg7zygJSopDF4b6a4j2cnrHeIRkWC3rwfye3bdFM+oQAL8gzzR5kN1a3GhaK6/UYYjOzekbw==,iv:sodnAW/18eo9IN74D2prZQJiv2cGiQ9igGylAo+3B2c=,tag:Ev5Jgk1jvODA9gI1wuGSPA==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T16:29:53Z"
    mac: ENC[AES256_GCM,data:nGIEuSIx/GChej+bdYRLHgGh809UeiI1iWiYphy9b62I/YijcFqqo2XDjb6XZcFbrvRl0tUEHRBGIYgIlq7lIs3fIGlM6XYmhCJ3+OqvdSz7YyTWqU0qTVZA/cGpglrSb98YPOkQwv5M77n0QTN7qaY+daMVbJuU3Qe1jW9NvkQ=,iv:7HQO7AJ8n0jPEf7dcImg7s1qlmjljAD2gu46ehSZmnE=,tag:wRIrQ4zfNc97gCf5sFNPqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
