apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: default
type: Opaque
stringData:
    gatewayToken: ENC[AES256_GCM,data:tMnGKc0Qv2zTZCq1DPkybOCgkXS51wtaHkkP80fYFyLJlMAZBtrhgqNKI+Pb/n1r0onhTAuP92gAGl57SG4sBw==,iv:/maFuB/QNEXE5fZoCLh1bBXs/rHErF7L4o6ohvKZOJI=,tag:hpnKCrk/TMHd9ZsmvPlZNg==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T08:38:34Z"
    mac: ENC[AES256_GCM,data:YGahNSVOoYlLVnKybUhMQUbOT3fYujEnx2huUntYCUO69B3ABegrUNIB9A7YB40D4DNFLDOYp+yR4+67zJcCCdSe04oSh+6pXrs0U1D03Pwdj4Sudw+pcimFwlOdyRvxVpwtmBE5p2Eq4B7IfHNhh4BonolbjfCYLE0Py3936Xs=,iv:V8v7/TqIsOxzjyyX3NnhOGDutUeTMgPncHk7oeCWpFo=,tag:+f7blYMH0qBPESvdBjG+Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
