apiVersion: v1
kind: Secret
metadata:
    name: open-terminal-secret
    namespace: default
type: Opaque
stringData:
    apikey: ENC[AES256_GCM,data:2M79kXMa3GyKyEoiQI3tbBT6QHR7Ylqbp3sRYQRYcUZe5xWV,iv:xpX/ocsOcmKjKC8oI5LmhooqN6G6hYxv/URtj0fst9M=,tag:ErTBQCsqcAVtzVX4+oBfmQ==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T21:06:05Z"
    mac: ENC[AES256_GCM,data:bZO1nKpkxl3VipnKHfoaaf8qW/w7x700xQ26SDLF1RW1onPGe0uccGVTBDqAXTj5VxMFR9zZ2ybHOFsemIp1P5d6oh7FVJPkqlSgAxQG1sJh6sN1R63U3w1vzaYr4P7fEtAbdRfLJLobVyQqJSXj1njenqIAIirCRggAnu6Jg9c=,iv:+zIROl1iDuiHoqDzOs5E3WUiw+hn1XI3JqYWFrLVFcs=,tag:fsbKJTJ1cknWiBZf2oQ/gA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
