apiVersion: v1
kind: Secret
metadata:
    name: postgres-forgejo-secret
    namespace: default
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:GrBZ5hoBLg==,iv:mZexuYt2nbwd+fWBVK8OFhZDNZMRjytf56z41aQvKfU=,tag:Hpb8WNWKzdb9Qdx471QDMg==,type:str]
    password: ENC[AES256_GCM,data:xfx37G1Pt62JHxG0V7LAI7c8fw+RfbTb+MhK4pu97sSOzg==,iv:2FzUAMk355N7LjO1cf1giQDuQ/a9BwRjhYBqD6iB5as=,tag:0UBnD1bhvJeuWktbMSlxiQ==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T08:47:17Z"
    mac: ENC[AES256_GCM,data:3uMlzCygobjpeUoelIOv5kfHHg7Adpwmn1rQ6sX0v/fW6eqcQ/GZrGPECUWP9/xE31ET2iTtzvZOFSc4t91I57gDJkjuZWdUnA6AwmhWjR9lmZxboiwZf2nMUTRI43fv3V3qFHJj2TZgO0YY7ZRpJ4f+ANLTGm2svd7QxeWFYb8=,iv:N8w3F54D9ResRjNxSWwKHU/EvhissB6jkyMDMxLAZmM=,tag:cvxadkWBSI+hsYZs8BPxEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
