apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: default
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:k48n7ee/iyc=,iv:qbQtvhqiwjxQXFxaOFOfSUDEA6WWahbuETu03BAj0HA=,tag:p0bsLDsz8+J4xm6VeDNzNg==,type:str]
    password: ENC[AES256_GCM,data:zxZ2mcMBL8UBwPXN+Hk/8r3lcMBxvK2yJn5bgPhYBOhvDWsv,iv:FkTn6puQZKai2RAHYUSnk1kePylUY8Bzy9psghD3qZI=,tag:77Td/xp+Oq3Ul5CWMWP0kA==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T22:26:12Z"
    mac: ENC[AES256_GCM,data:M7PCKV1PBlBw5kqIZXm4oHyzI/XFpSkpqpI1jksOuiWnmaAvIgaAVDPpdcpuYTiL8/BGkL6m9uyE176/mNoVuK5sDo6pCHsHKBoL2y6qPIYK+HHCnzagwESphgjzVmdFb5gZsaY5qVLJb4SNHNOn6IRpufRfO1pfg48TyelnrZQ=,iv:ECQYhlWRKNm4+i7RGBxojpkI4MvWl1SLglUeinNSxzk=,tag:WOB554+1fGsFNYb/wEIxKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
