apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:dJPzZkKgfw8=,iv:gkSn3tzLJy/nXOlcR/vxX4nevPzrvJ8l3RvwtL3K0ts=,tag:RZoDdsIMsGm1UDfqC/0NOQ==,type:str]
    password: ENC[AES256_GCM,data:zxZ2mcMBL8UBwPXN+Hk/8r3lcMBxvK2yJn5bgPhYBOhvDWsv,iv:FkTn6puQZKai2RAHYUSnk1kePylUY8Bzy9psghD3qZI=,tag:77Td/xp+Oq3Ul5CWMWP0kA==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T22:17:26Z"
    mac: ENC[AES256_GCM,data:TbU1qcm0WXhUzhKRAK4ED9qMQcx430ykx+dSevPHNcculMJkEYxx7vy+KzteMz99pfsHOEos0qyF3fxrWKonjMhA7Q36tF8NyQb0tGsd+iCuOX+Xl/JLSq4GwJv6//2FpB+a/gJa4ln/3C4Az5EjGB2QNQK1tYCCebblYJX6/9A=,iv:mbLXnhy6dyNSKQUjK6tcHWKa4rjFf/vlDbFgrUaqi2E=,tag:oqfQujKCmahdAHXyxFeziw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
