apiVersion: v1
kind: Secret
metadata:
    name: postgres-open-webui-secret
    namespace: default
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:G570CBU0MOSf,iv:Kof2IZ2l4CcrdTcZ5xQtwfZU0e/UmopB+B2unFe1DwI=,tag:TXLdz6l6h6cUjrWtXKKpAw==,type:str]
    password: ENC[AES256_GCM,data:UF/0CZZXYgXHMsttRhNJ6OFy3qRRouMq7pTMhiBZv5bKe/7TZFbbRGSzQw==,iv:e5nmk8Tlun2ohWE8j4r1z1+CWWkbUGRiwD1Fjh8tyX8=,tag:2Q1cXRd6Yy2samJl8en/rA==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T16:40:01Z"
    mac: ENC[AES256_GCM,data:UzYVmnUEZObR6i6G/aqGGDFF8TowfR9Ky8it35tZ1hkYZ9YNcqkLVhLuuOHVKn1yGJxqd6XOhb10KMIu4Ao7auZiB/4hzPL3ZNUtT9pP2Ffzo0g+J8kfUFQXGe4deCTx0Mmm8koGoIIPValDlMN4IJgXUwR9VB61Lb/xktm4daA=,iv:fGGHMAbVVz+E8qYqiFMp3ihM+LaxnfxUuswRwawj+NE=,tag:jaXvH8TCG7xpmmfvf07uNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
