apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XKOFVCzuwGl2sc/NejrbAblZwTfMcYQrzRv9P0JvceTV,iv:6zEkEQhwi4WRN42WpZxbwCNrFkkf5geiHCxvyMorf+w=,tag:5nhR6y3lNHxjY7oahHK3sw==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:AdJfqoY=,iv:Ym/daiVW1rs1+nw2TOM+KR5UwqN1zOMckx7QbTcItMs=,tag:XfWBK1eGYB7GHG3XPvnNXQ==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:OU/tGpROcmLKuoJo0nq0sP8u1YB4d2h6BIbUEaPVwazabA==,iv:g4EtqFpp7FpvGOf0aNcat2sBgCTwPKoHV9CCPE2MAdc=,tag:Z29qPEG/DYLqvL7cWZ+VZw==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:3diEIRMU,iv:iuyakDaY8u5ppufl3UnW3TSKdm4va03o+7ypKZO0zGQ=,tag:H3zktCtZZwemaGLbvLub0Q==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:mwwiiLmJi9tmIuDjwpNuhbQalvFTnQ3xKnNAJHY/3VuZiXwnGqNDSJn6s4EHF7SqHNi7A+OzHFKF96mMbhk/ALWVfkv28V/XRavCrWzo+kZA+5y7cy5yUli4hsDU,iv:PteSLfI/TrvjTn8wKf8GRGT4vnkeUEEuI3lXqmFwRkM=,tag:duqH/mMavpO1vcu4UCfTdA==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T21:28:09Z"
    mac: ENC[AES256_GCM,data:/gQd4aQdvHWi5k5ZEO/dM24eUhqMYpEL4VB6A3pQcTtRl+FGH6X87y11iYZlIb/QupkxL7+ucmVM+wOsAg2cd1ofSE8xJSeVhredT6RdYKdimlduECRBcVDjODUkV/kpx2dAeFLCSRvHmChI5aDdvG67eH7w7d+Npioe6xD0KbU=,iv:BTOm/upi9RDbuSR8ASP4bH3s+9a1F2Tz7ImBm9ao024=,tag:23hCn4npwYVvWUtznhFCpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
