apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:KBgK2p+clIGu+s45WZCQ6tcSrbIDvfJ6fgw7pvw+XRxsRmcngiM7acP6Q20=,iv:KU7FcHKWriPZWAEk2aThbppVwlG5cWv0z5MEKLnir8I=,tag:z5A69MMKW4Ai/XjLOpV2NQ==,type:str]
    addresses: ENC[AES256_GCM,data:n8TgEmfupK5nSFMFU2Bscw==,iv:MxvTnQgpGctXvSKZ0+oyoGaRKqsK9tGhG2bK3E+syMQ=,tag:D4xZVCmXytjY/VWCxWwC3Q==,type:str]
    cities: ENC[AES256_GCM,data:l16PEDO6RU/xmw==,iv:DJ5Ydv0nWI4wrX7e56BdkrEQr51pTz8G8SXf4gVurMk=,tag:Yh62E9bdnoBWDtAME0nZhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T19:31:47Z"
    mac: ENC[AES256_GCM,data:ne6wwLHHfryKkiot+Jtj4QQ5sWI8cgMQEHVnpTPplKURj63IyX4/5xO2XZCrVt4++KjebhrlTxUMVDpe03r8RuVCE7NRyj4ne/YFGYEzwxorBOWgz0g1f7gxva5h0YuV7gp/eNb/EAXTjexIbzSlqZwfz/W3kYuVMVwzN/gjn+o=,iv:e9eLsKoD+Fl1xBE/dSEKIulUgv7OImwum1YiZKjyZog=,tag:LQjGf21gZ7NFNw6tqMUbDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
