apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: default
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:KBgK2p+clIGu+s45WZCQ6tcSrbIDvfJ6fgw7pvw+XRxsRmcngiM7acP6Q20=,iv:KU7FcHKWriPZWAEk2aThbppVwlG5cWv0z5MEKLnir8I=,tag:z5A69MMKW4Ai/XjLOpV2NQ==,type:str]
    addresses: ENC[AES256_GCM,data:20ovctnvkOdaF/tOcA==,iv:WLelrdwx59hkuETRscSfbecoxPQvsZdvmAXXZmhHE0k=,tag:Tq76FYvg+6MvqzS5yPrm5Q==,type:str]
    cities: ENC[AES256_GCM,data:l16PEDO6RU/xmw==,iv:DJ5Ydv0nWI4wrX7e56BdkrEQr51pTz8G8SXf4gVurMk=,tag:Yh62E9bdnoBWDtAME0nZhA==,type:str]
    #ENC[AES256_GCM,data:8+6f4VqIDeO+X04PZaFKhTpFl+M1082pzbXySxWHVxLVfZgdmQM=,iv:a9qGiAASpUqQfSHpKfNoFEKN71fK5ZBRCb/aldsJgAQ=,tag:t9qEIx9Y5xoEk/gQOO4uSQ==,type:comment]
    #ENC[AES256_GCM,data:wRMd3EQ13G8ueJx7kOnLkwvB279uyG7N9DQqufHrKc3fT3j6iOf8y3/lCDrOvyjBjvxwCnpoMotmHysneQ==,iv:WLbv9sVVOYOLZfaBnUorEPx1qAxMi503oTvBeoRaB30=,tag:8cqgZF8TQdxB92OLUDV1ww==,type:comment]
    device-name: ENC[AES256_GCM,data:ufYSCrM9LTKa1Nw=,iv:C7iClp6hWK5vYqfloQzVM7aWMnhuzdcPtCtvB1uriLM=,tag:Mx6fzrWBic29HU3du9ZwIg==,type:str]
sops:
    age:
        - recipient: age1rg25eke6v6mm6j3kn7pzftlp39hknp5l42q9ht604n84upj5kp4stmqtxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXFQTXlhc3dJZXVEb0dk
            b3R0cUI3RC9TZUtVTG5yVTlKc0Vkd1E2NnpvCldJVDNjTFAzVDI5Q1BBdzUzRlND
            aTF4Skl3VXNqRzl6andqU3E0Vmc2RmcKLS0tIGs0YUhkTi9RSDlMREI5SjhCT1hx
            L2dVQUFqakdzTFN1MlB6RXFRU0hKU3MKclynxaKg+sL7v7Qz9+W8T78KjNo7ryVy
            LAL33wnNj0clWs370A+2kqKUDiVqQgvg688G7nx727/MBieE7lTgNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T11:57:32Z"
    mac: ENC[AES256_GCM,data:MauKiCCrkmreHWh8xDTc9qSWG75adFGgQCmiOQvH0q5k6yCORNrzicRPvw7JJNouZSY+9CLrSH3aoFiC2Sa47/2GwYfwcT7BaZU4VYhNX1TTWP2BPrc5UO1bXTb/aNmIjYX5FWs+OPyDqXh5JOCPS90Nu6Z+DLNXPuaSTg9N/oo=,iv:cQUA2xU82sOtTqhGg5upwsUudkZ20DbuNp65AeFVa08=,tag:ze7HDprXE4YlmospqwrXDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
