apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    apps.kubernetes.io/name: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
