apiVersion: batch/v1
kind: Job
metadata:
  name: pg-migrate-dump
spec:
  template:
    spec:
      nodeSelector:
        network: fast
      restartPolicy: Never
      containers:
        - name: pg-migrate-dump
          image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
          env:
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: out
              mountPath: /out
          command: 
            - sh
            - -c
            - pg_dumpall
              --host=$PGHOST
              --database=$PGDATABASE
              --port=$PGPORT
              --username=$PGUSERNAME
              > /out/dump
      volumes:
        - name: out
          nfs:
            server: datasphere
            path: /Root/Volumes/out
  backoffLimit: 4
