apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: default
spec:
  selector:
    matchLabels:
      app: nextcloud
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      nodeSelector:
        network: fast
      containers:
        - name: nextcloud
          image: nextcloud:34.0.0
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              # memory: 100Mi
          env:
            - name: POSTGRES_HOST
              value: postgres15:5432
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: initial
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nc.home
            - name: REDIS_HOST
              value: valkey
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud
              mountPath: /var/www/html
            - name: nextcloud-files
              mountPath: /files
            - name: nextcloud-media
              mountPath: /media
      securityContext:
        fsGroup: 33
      volumes:
        - name: nextcloud
          nfs:
            server: datasphere
            path: /Root/Volumes/nextcloud
        - name: nextcloud-files
          nfs:
            server: datasphere
            path: /Root/Files
        - name: nextcloud-media
          nfs:
            server: datasphere
            path: /Root/Media
